### ISSUE TITLE
/ipsec 中没有内容

### ISSUE THREAD

**Issue by PointerWild** [zhangke5959/strongswan#1]
您好：
我执行了前三步，但是，在 /ipsec 中并没有任何内容。麻烦问一下，这个我是理解错了吗？
可以帮我解决一下吗？
 
1，在strongswan目录运行autogen.sh命令。生成configuie命令
 2，在主机的根系统上创建 /ipsec 目录，添加权限 chmod 777 /ipsec 
3，在strongswan目录运行autogen.sh命令。配置，编译及安装strongswan

**Comment by PointerWild** [comment]
我解决了，因为之前一直报错 找不到 openssl/ 下的一个头文件，我更新了openssl之后，就好了。

**Comment by whbwyj** [comment]
你好，我遇到的情况跟你的一样，请问你是怎么操作好的？我这里没报错。在 /ipsec 中并没有任何内容。
