### ISSUE TITLE
ubuntu 18.04编译出现error: ‘NID_sm2p256v1’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by hongruixing** [zhangke5959/strongswan#12]
我在编译的过程中，出现如下错误：
mv -f $depbase.Tpo $depbase.Plo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../../.. -I../../../../src/libstrongswan -DFIPS_MODE=0 -rdynamic -g -O2 -Wall -Wno-format -Wno-format-security -Wno-pointer-sign -include /study/strongswan/config.h -MT openssl_ec_diffie_hellman.lo -MD -MP -MF .deps/openssl_ec_diffie_hellman.Tpo -c openssl_ec_diffie_hellman.c  -fPIC -DPIC -o .libs/openssl_ec_diffie_hellman.o
openssl_ec_diffie_hellman.c: In function ‘openssl_ec_diffie_hellman_create’:
openssl_ec_diffie_hellman.c:619:41: error: ‘NID_sm2p256v1’ undeclared (first use in this function); did you mean ‘NID_secp256k1’?
    this->key = EC_KEY_new_by_curve_name(NID_sm2p256v1);
                                         ^~~~~~~~~~~~~
                                         NID_secp256k1
openssl_ec_diffie_hellman.c:619:41: note: each undeclared identifier is reported only once for each function it appears in
Makefile:623: recipe for target 'openssl_ec_diffie_hellman.lo' faile
是我的openssl版本不对，还是需要gmssl

**Comment by ruce-fan** [comment]
需要gmssl，源码根目录有个build.sh脚本，参考一下

**Comment by Tapanta2025** [comment]
> 
> 
> 我在编译的过程中，出现如下错误：
> mv -f $depbase.Tpo $depbase.Plo
> libtool: compile: gcc -DHAVE_CONFIG_H -I. -I../../../.. -I../../../../src/libstrongswan -DFIPS_MODE=0 -rdynamic -g -O2 -Wall -Wno-format -Wno-format-security -Wno-pointer-sign -include /study/strongswan/config.h -MT openssl_ec_diffie_hellman.lo -MD -MP -MF .deps/openssl_ec_diffie_hellman.Tpo -c openssl_ec_diffie_hellman.c -fPIC -DPIC -o .libs/openssl_ec_diffie_hellman.o
> openssl_ec_diffie_hellman.c: In function ‘openssl_ec_diffie_hellman_create’:
> openssl_ec_diffie_hellman.c:619:41: error: ‘NID_sm2p256v1’ undeclared (first use in this function); did you mean ‘NID_secp256k1’?
> this->key = EC_KEY_new_by_curve_name(NID_sm2p256v1);
> ^~~~~~~~~~~~~
> NID_secp256k1
> openssl_ec_diffie_hellman.c:619:41: note: each undeclared identifier is reported only once for each function it appears in
> Makefile:623: recipe for target 'openssl_ec_diffie_hellman.lo' faile
> 是我的openssl版本不对，还是需要gmssl

需要gmssl，源码根目录有个build.sh脚本，参考一下

**Comment by hongruixing** [comment]
问题已经解决，谢谢

**Comment by hancm** [comment]
> 问题已经解决，谢谢

请问下用openssl1.1.1是不是就不需要用gmslg插件了？openssl1.1.1做了国密的功能。
