### ISSUE TITLE
出现12[KNL] received netlink error: Function not implemented (38)

### ISSUE THREAD

**Issue by hongruixing** [zhangke5959/strongswan#14]
运行testing/tests/gmalg$下面的run.sh 出现
[ENC] parsed QUICK_MODE response 3255607844 [ HASH SA No KE ID ID ]
[CFG] selected proposal: ESP:SM4_CBC_128/HMAC_SM3/CURVE_SM2/NO_EXT_SEQ
12[KNL] received netlink error: Function not implemented (38)
12[KNL] unable to add SAD entry with SPI ca0a6bc9 (FAILED)
12[KNL] received netlink error: Function not implemented (38)
12[KNL] unable to add SAD entry with SPI c063a638 (FAILED)
[KNL] received netlink error: Function not implemented (38)
12[IKE] unable to install inbound and outbound IPsec SA (SAD) in kernel
12[KNL] deleting policy 192.168.80.21/32 === 192.168.10.92/32 in failed, not found
12[KNL] deleting policy 192.168.80.21/32 === 192.168.10.92/32 fwd failed, not found
12[ENC] generating INFORMATIONAL_V1 request 775364196 [ HASH N(NO_PROP) ]
12[NET] sending packet: from 192.168.10.92[500] to 192.168.80.21[500] (92 bytes)
[KNL] unable to add SAD entry with SPI ca0a6bc9 (FAILED)
[KNL] received netlink error: Function not implemented (38)
[KNL] unable to add SAD entry with SPI c063a638 (FAILED)
[IKE] unable to install inbound and outbound IPsec SA (SAD) in kernel
initiate failed: establishing CHILD_SA 'host-host' failed

**Comment by hongruixing** [comment]
solved

**Comment by hcjjmt** [comment]
> solved

请问怎么解决的啊，我也遇到同样的问题

**Comment by PopMini** [comment]
> solved

same issue.  Hope your solutions.
