### ISSUE TITLE
ipsec sa

### ISSUE THREAD

**Issue by wangyongzx** [zhangke5959/strongswan#15]
请问一下我host-host的client一直打印
07[ESP] could not find an outbound IPsec SA for reqid {5}, dropping packet；这是什么导致的
![image](https://user-images.githubusercontent.com/44894500/119509235-09ffa580-bda3-11eb-8435-cdfde4f05e3b.png)

**Comment by wangyongzx** [comment]
已经解决

**Comment by debenv** [comment]
如何解决的，能详细描述下吗？
